import "./globals.css"
import Navigation from "@/components/navigation"
import Footer from "@/components/footer"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme='cyberpunk'>
      <body>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  )
}
